### ISSUE TITLE
python3 errors

### ISSUE THREAD

**Issue by martinspears** [akestoridis/zigator#1]
~/workarea/zigator$ zigator -v
Traceback (most recent call last):
  File "/home/sail/.local/bin/zigator", line 5, in <module>
    from zigator.entry_point import entry_point
  File "/home/sail/.local/lib/python3.8/site-packages/zigator/__init__.py", line 38, in <module>
    from .main import main
  File "/home/sail/.local/lib/python3.8/site-packages/zigator/main.py", line 23, in <module>
    from . import parsing
  File "/home/sail/.local/lib/python3.8/site-packages/zigator/parsing/__init__.py", line 21, in <module>
    from .main import main
  File "/home/sail/.local/lib/python3.8/site-packages/zigator/parsing/main.py", line 23, in <module>
    from .pcap_file import pcap_file
  File "/home/sail/.local/lib/python3.8/site-packages/zigator/parsing/pcap_file.py", line 23, in <module>
    from .phy_fields import phy_fields
  File "/home/sail/.local/lib/python3.8/site-packages/zigator/parsing/phy_fields.py", line 20, in <module>
    from .mac_fields import mac_fields
  File "/home/sail/.local/lib/python3.8/site-packages/zigator/parsing/mac_fields.py", line 25, in <module>
    from scapy.all import Dot15d4CmdCoordRealignPage
ImportError: cannot import name 'Dot15d4CmdCoordRealignPage' from 'scapy.all' (/usr/lib/python3/dist-packages/scapy/all.py)

**Comment by akestoridis** [comment]
It looks like you are using an old version of Scapy. The `Dot15d4CmdCoordRealignPage` class was added in version 2.4.3.dev567 of Scapy (see https://github.com/secdev/scapy/commit/a3d691f5b7f51bfc5248e4b6fbb40c77139f26c3)
